# ----------------------------------------------------------------------
# Helm chart values for combined IBM Spectrum Scale CNSA/CSI Deployment
# ----------------------------------------------------------------------
# IBM Spectrum Scale CNSA 5.1.0.3 / CSI 2.1.0 release 
# ----------------------------------------------------------------------
# DISCLAIMER:
# These Helm charts are only intended to provide ease of use for an 
# initial deployment (helm install) of 
# IBM Spectrum Scale Container Native Storage Access (CNSA) 5.1.0.3 
# and IBM Spectrum Scale CSI driver version v2.1.0 for 
# Proof of Concepts (PoCs), demos or any other form of evaluations
# where no further lifecycle managment and upgrade paths are considered. 
# They are explicitely not intended and not suported for 
# any production use!
# These Helm charts are not supported by the 
# IBM Spectrum Scale container native nor CSI offerings 
# and are outside the scope of the IBM PMR process. 
# These Helm charts are provided on an "AS IS" BASIS, WITHOUT WARRANTIES 
# OR CONDITIONS OF ANY KIND, either express or implied, including, 
# without limitation, any warranties or conditions of TITLE, 
# NON-INFRINGEMENT, MERCHANTABILITY, or FITNESS FOR A PARTICULAR PURPOSE. 
# You are solely responsible for determining the appropriateness of 
# using or redistributing the Work and assume any risks associated with
# Your exercise of permissions under this License.
# Note, that these Helm charts do not support any lifecycle management 
# of IBM Spectrum Scale Container Native Storage Access and 
# IBM Spectrum Scale CSI driver, especially, the 
# helm upgrade|rollback|uninstall features are not supported and are not
# expected to work. 
# You need to follow the offcial IBM documentation to perform any 
# changes or upgrades to the deployment.
# ----------------------------------------------------------------------

#########################################################
## CUSTOMER ENVIRONMENT MINIMUM REQUIRED CONFIGURATION ##
#########################################################

## -----------------------------------------
##  IBM Spectrum Scale CNSA: Image Registry
## -----------------------------------------

# REQUIRED: imageRegistry as FQDN[:port] to pull the IBM Spectrum Scale CNSA images from (e.g. OpenShift internal registry: "image-registry.openshift-image-registry.svc:5000")
imageRegistry: "image-registry.openshift-image-registry.svc:5000"
# OPTIONAL: imageRegistryNamespace: Namespace used in the internal image registry; if set to "" the release namespace for the deployment will be used (e.g. ibm-spectrum-scale)
imageRegistryNamespace: ""
# OPTIONAL: imageRegistrySecret: This is the name of the imagePullSecret required for accessing an external image registry to pull images, e.g. created with: 
# kubectl create secret docker-registry [name] -n [namespace] --docker-server=[registry] --docker-username=[name] --docker-password=[password/token] --docker-email=[email]
# See https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
# imageRegistrySecret: "spectrumscale-registrykey"
imageRegistrySecret: ""

## --------------------------------------------------------
##  IBM Spectrum Scale CNSA: Primary Storage Configuration
## --------------------------------------------------------

# REQUIRED: primaryFilesystem: refers to the local file system mounted from a remote storage cluster that will also host the IBM Spectrum Scale CSI primary fileset
# name: name of the file system in the local IBM Spectrum Scale CNSA cluster (Note: "_" is not allowed as part of the local file system name)
#       IMPORTANT: the local "name" must comply with DNS label name rules, see https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#dns-label-names)
# mountPoint: mount point of the file system in the local IBM Spectrum Scale CNSA cluster; must start with "/mnt"
# storageFs: name of the file system on the remote IBM Spectrum Scale storage cluster
primaryFilesystem:
  name:           "fs1"
  mountPoint:     "/mnt/fs1"
  storageFs:      "ess_fs1"

# REQUIRED: primaryRemoteStorageCluster: refers to the remote storage cluster that will also host the IBM Spectrum Scale CSI primary file system
# host: FQDN or IP address of the GUI host for the remote IBM Spectrum Scale storage cluster
# secretName: name of the K8s secret in the release namespace that holds the credentials for this remote storage cluster
# cacert: Name of ConfigMap containing the CA certificate of the storage cluster GUI. If not specified, the default OpenShift Container Platform CA or Red Hat CA bundle is used.
# insecureSkipVerify: To skip TLS verification, set insecureSkipVerify to true. Recommended default is "false" to enable TLS verification for storage cluster GUI!
# contactNodes (optional): list of contact nodes in the remote IBM Spectrum Scale storage cluster. If not specified, the operator will pick 3 nodes from the storage cluster. 
primaryRemoteStorageCluster:
  gui:
    host:               "remote-scale-gui.mydomain.com"
    secretName:         "cnsa-remote-gui-secret"
    #cacert:             "cacert-storage-cluster"
    insecureSkipVerify: true
  #contactNodes: [storageCluster1node1, storageCluster1node2, storageCluster1node3]

## -----------------------------------------------------------
##  IBM Spectrum Scale CSI: Primary File System Configuration
## -----------------------------------------------------------

# REQUIRED: primaryCluster: local IBM Spectrum Scale CNSA cluster that will also mount the primary file system to store IBM Spectrum Scale CSI configuration data
primaryCluster:
  # REQUIRED: localClusterId: Cluster ID of the local IBM Spectrum Scale CNSA cluster (will be specified with helm install --set primaryCluster.localClusterId="$CLUSTERID")
  # REQUIRED: localGuiHost: Kubernetes service name of local IBM Spectrum Scale CNSA GUI
  # REQUIRED: localCsiSecret: Kubernetes secret with username/password for csi-user in the GUI of the local IBM Spectrum Scale CNSA cluster
  # OPTIONAL: localSecureSslMode: true/false
  # OPTIONAL: localCAcert: Name of CA cert configmap for the GUI of the local IBM Spectrum Scale CNSA cluster
  localClusterId:         "needs-to-be-read-after-CNSA-deployment"   
  localGuiHost:           "ibm-spectrum-scale-gui.<replace-with-CNSA-namespace>"
  localCsiSecret:         "csi-local-secret"
  localSecureSslMode:     false
  localCAcert:            ""
  # OPTIONAL: primaryFset: Leave empty as "" for default IBM Spectrum Scale CSI fileset name which is "spectrum-scale-csi-volume-store"
  # OPTIONAL: primaryFsetInodeLimit: Leave empty as "" for using defaults for the IBM Spectrum Scale CSI fileset
  primaryFset:            ""
  primaryFsetInodeLimit:  ""
  # REQUIRED: primaryRemoteClusterId: Cluster ID of the remote IBM Spectrum Scale storage cluster if primaryFs is a remote cluster file system
  # REQUIRED: primaryRemoteCsiSecret: Name of the K8s secret with username/password for CSI to access the GUI on the remote IBM Spectrum Scale storage cluster
  # OPTIONAL: primaryRemoteSecureSslMode: true/false
  # OPTIONAL: primaryRemoteCAcert: Name of CA cert configmap for accessing the GUI of the remote IBM Spectrum Scale storage cluster
  primaryRemoteClusterId:       "2303539379337927879"
  primaryRemoteCsiSecret:       "csi-remote-secret"
  primaryRemoteSecureSslMode:   false
  primaryRemoteCAcert:          ""

#################################################
## CUSTOMER ENVIRONMENT OPTIONAL CONFIGURATION ##
#################################################

## ------------------------------------
##  IBM Spectrum Scale CNSA: Call Home
## ------------------------------------

# OPTIONAL: To enable IBM Call Home support, remove the first "#" character on each line of below "callHome:" and provide the required information
# acceptLicense: If you agree, please respond with "true" for acceptance, else with "false" to decline.
# companyName; Name of the company to which the contact person belongs.
# This name can consist of any alphanumeric characters and these non-alphanumeric characters: '-', '_', '.', ' ', ','.
# customerID: the IBM ID received by the customer upon purchasing a IBM Spectrum Scale license / or DEVLIC (developer edition) or TRYBUY (test edition)
# This can consist of any alphanumeric characters and these non-alphanumeric characters: '-', '_', '.'.
# companyEmail: a group or task e-mail address to be contacted by IBM Support
# countryCode: two-letter uppercase country code in the ISO 3166-1 alpha-2 format (e.g. US for USA, DE for Germany).
# type: Marks the cluster as a "test" or a "production" system. In case this parameter is not explicitly set, the value is set to "production" by default.
# If a proxy should be used for uploads provide the following information / otherwise leave "#" in place to not use a proxy 
#   host of proxy server as hostname or IP address
#   port of proxy server
#   secretName of a basic-auth secret, which contains username and password for proxy server
#   Leave "#" if no authentication to the proxy server is needed.
callHome:
#  acceptLicense: true
#  companyName: "company"
#  customerID: "123456-kl"
#  companyEmail: "smith@email"
#  countryCode: "de"
#  type: production | test
#  proxy:
#    host: "192.1.1.1"
#    port: "2345"
#    secretName: "proxy-secret"

## ---------------------------------------
##  IBM Spectrum Scale CNSA: Host Aliases
## ---------------------------------------

# OPTIONAL: hostAliases for environments where DNS cannot resolve the nodes of the remote IBM Spectrum Scale storage cluster. Uncomment and replicate list items to add more aliases.
hostAliases:
#  - hostname: "my-hostname1.mydomain.com"
#    ip: "10.11.12.101"

## ------------------------------------------------------
##  IBM Spectrum Scale CNSA: Node Selector Configuration
## ------------------------------------------------------

# REQUIRED: nodeSelector ensures to deploy IBM Spectrum Scale CNSA pods on nodes only matching the following node labels
# The Operator will check that a node has all labels defined present in order to deploy IBM Spectrum Scale CNSA pods on this node.
# The default below deploys IBM Spectrum Scale CNSA pods on all OpenShift "worker" nodes
nodeSelector:
  node-role.kubernetes.io/worker: ""

## ----------------------------------
##  IBM Spectrum Scale CNSA: Profile
## ----------------------------------
profile:
  pagepool:                           "1G"
  ignorePrefetchLUNCount:             "yes"
  workerThreads:                      1024
  maxFilesToCache:                    "128K"
  maxStatCache:                       "128K"
  maxblocksize:                       "16M"
  initPrefetchBuffers:                128
  prefetchTimeout:                    30
  prefetchPct:                        25
  prefetchMaxBuffersPerInstance:      1024
  controlSetxattrImmutableSELinux:    "yes"
  enforceFilesetQuotaOnRoot:          "yes"

## -----------------------------------------------------
##  IBM Spectrum Scale CSI: Node Selector Configuration
## -----------------------------------------------------

# The IBM Spectrum Scale CSI Operator will check that a node has all the labels defined below in order to deploy IBM Spectrum Scale CSI pods on this node.
# REQUIRED: csiNodeSelectorBase "scale: true" is the default node label for deploying Spectrum Scale CSI pods on a node (DEFAULT / leave as is)
csiNodeSelectorBase:
  key:    "scale"
  value:  "true"
# OPTIONAL: csiNodeSelectorProvisioner is an additional node label to run the IBM Spectrum Scale CSI Provisioner pods
# on a specifc subset of CSI nodes (highly reliable OpenShift infrastructure nodes), e.g. key: "infranode", value: "1"
# Set only if required. Otherwise set key: "" to be ignored.
csiNodeSelectorProvisioner:
  key:    ""
  value:  ""
# OPTIONAL: csiNodeSelectorAttacher is an additional node label to run the IBM Spectrum Scale CSI Attacher pods
# on a specifc subset of CSI nodes (highly reliable OpenShift infrastructure nodes), e.g. key: "infranode", value: "2"
# Set only if required. Otherwise set key: "" to be ignored.
csiNodeSelectorAttacher:
  key:    ""
  value:  ""

## ---------------------------------------------------
##  IBM Spectrum Scale CSI: Tolerations Configuration
## ---------------------------------------------------
# https://www.ibm.com/docs/en/spectrum-scale-csi?topic=operator-tolerations

# OPTIONAL: csiTolerations is an array of Kubernetes tolerations distribued to IBM Spectrum Scale CSI pods
# https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/
csiTolerations:
#  - key: "key1"
#    operator: "Equal"
#    value: "value1"
#    effect: "NoExecute"
#    tolerationSeconds: 3600
#  - key: "key2"
#    operator: "Equal"
#    value: "value1"
#    effect: "NoExecute"
#    tolerationSeconds: 3600
