# ----------------------------------------------------------------------
# Default Helm chart values for 
# IBM Spectrum Scale Container Native Storage Access v5.1.1.1
# ----------------------------------------------------------------------
# DISCLAIMER:
# These Helm charts are only intended to provide ease of use for an 
# initial deployment (helm install) of 
# IBM Spectrum Scale Container Native Storage Access (CNSA) 5.1.1.1 
# and IBM Spectrum Scale CSI driver version v2.2.0 for 
# Proof of Concepts (PoCs), demos or any other form of evaluations
# where no further lifecycle managment and upgrade paths are considered. 
# They are explicitly not intended and not suported for 
# any production use!
# These Helm charts are not supported by the 
# IBM Spectrum Scale container native nor CSI offerings 
# and are outside the scope of the IBM PMR process. 
# These Helm charts are provided on an "AS IS" BASIS, WITHOUT WARRANTIES 
# OR CONDITIONS OF ANY KIND, either express or implied, including, 
# without limitation, any warranties or conditions of TITLE, 
# NON-INFRINGEMENT, MERCHANTABILITY, or FITNESS FOR A PARTICULAR PURPOSE. 
# You are solely responsible for determining the appropriateness of 
# using or redistributing the Work and assume any risks associated with
# Your exercise of permissions under this License.
# Note, that these Helm charts do not support any lifecycle management 
# of IBM Spectrum Scale Container Native Storage Access and 
# IBM Spectrum Scale CSI driver, especially, the 
# helm upgrade|rollback|uninstall features are not supported and are not
# expected to work. 
# You need to follow the offcial IBM documentation to perform any 
# changes or upgrades to the deployment.
# ----------------------------------------------------------------------
# Deploy Helm chart into its own namespace, e.g.
# helm install ibm-spectrum-scale helm/ibm-spectrum-scale -n ibm-spectrum-scale
# with
#   ibm-spectrum-scale: Helm release name of the deployment, can be freely chosen
#   helm/ibm-spectrum-scale: Helm chart of IBM Spectrum Scale CNSA
#   -n ibm-spectrum-scale: Namespace of the deployment
# ----------------------------------------------------------------------
# Note: In the default configuration Spectrum Scale services will be deployed on 
#       all OpenShift worker nodes (a specific nodeSelector label can be added below).
# -----------------------------------------------------------------------------------

########################################
## CUSTOMER ENVIRONMENT CONFIGURATION ##
########################################

## See https://www.ibm.com/docs/en/scalecontainernative?topic=operator-custom-resource
## for additional information on the parameters used by the Custom Resource (CR).

## --------------------------------------------
##  IBM Spectrum Scale CNSA: License Agreement
## --------------------------------------------

# REQUIRED: User must accept the IBM Spectrum Scale license to deploy a CNSA cluster. 
# accept: By specifying true the user agrees to the terms and conditions set forth by 
#         the IBM Spectrum Scale Container Native Data Access/Data Management license located at
#         https://www14.software.ibm.com/cgi-bin/weblap/lap.pl?l=en&popup=y&li_formnum=L-CPES-C3MSKL&title=IBM%20License%20Agreement
# license: Enter either "data-access" (default) or "data-management" based on your granted license. 
#          Customers entitled to the Data Management Edition can use either "data-management" or "data-access". 
#          Customers entitled to the Data Access Edition can only use "data-access".
license:
    accept: false
    license: data-access

## --------------------------------------------------------
##  IBM Spectrum Scale CNSA: Primary Storage Configuration
## --------------------------------------------------------

# REQUIRED: The primaryFilesystem section refers to the local file system mounted from a remote storage cluster that will also host the IBM Spectrum Scale CSI driver primary fileset.
# name: Name of the file system in the local IBM Spectrum Scale CNSA cluster (Note: "_" is not allowed as part of the local file system name).
#       IMPORTANT: The local "name" must comply with DNS label name rules at https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#dns-label-names.
# mountPoint: Mount point of the file system in the local IBM Spectrum Scale CNSA cluster. Must start with "/mnt".
# storageCluster: Internal reference to corresponding section in primaryRemoteStorageCluster below which defines the details of the remote IBM Spectrum Scale storage cluster.
# storageFs: Device name of the file system on the remote IBM Spectrum Scale storage cluster used for the remote mount.
primaryFilesystem:
  name:           "fs1"
  mountPoint:     "/mnt/fs1"
  storageCluster: "storageCluster1"
  storageFs:      "ess_fs1"

# REQUIRED: The primaryRemoteStorageCluster section refers to the remote storage cluster that will also host the IBM Spectrum Scale CSI driver primary file system.
# name: Internal name for the storageCluster definition as referred to in the primaryFilesystem section above.
# host: FQDN or IP address of the GUI host for the remote IBM Spectrum Scale storage cluster.
# secretName: Name of the K8s secret that holds the IBM Spectrum Scale CNSA user credentials for this remote storage cluster.
# cacert: Name of ConfigMap containing the CA certificate of the storage cluster GUI. If not specified, the default OpenShift Container Platform CA or Red Hat CA bundle is used.
# insecureSkipVerify: To skip TLS verification, set insecureSkipVerify to true. Recommended default is false to enable TLS verification for storage cluster GUI!
# contactNodes (optional): List of contact nodes in the remote IBM Spectrum Scale storage cluster. If not specified, the operator will pick 3 nodes from the storage cluster. 
primaryRemoteStorageCluster:
  name:                 "storageCluster1"
  gui:
    host:               "remote-scale-gui.mydomain.com"
    secretName:         "cnsa-remote-gui-secret"
    #cacert:            "cacert-storage-cluster"
    insecureSkipVerify: false
  #contactNodes: [storageCluster1node1, storageCluster1node2, storageCluster1node3]

## -----------------------------------------------------------
##  IBM Spectrum Scale CNSA: Additional Storage Configuration
## -----------------------------------------------------------

# OPTIONAL: The addlFilesystems section refers to other local file systems mounted from a remote storage cluster (uncomment and replicate block to add more file systems).
# name: Name of the file system in the local IBM Spectrum Scale CNSA cluster (Note: "_" is not allowed as part of the local file system name).
#       IMPORTANT: The local "name" must comply with DNS label name rules at https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#dns-label-names.
# mountPoint: Mount point of the file system in the local IBM Spectrum Scale CNSA cluster. Must start with "/mnt".
# storageCluster: Internal reference to corresponding section in primaryRemoteStorageCluster or addlRemoteStorageClusters which defines the details of the remote IBM Spectrum Scale storage cluster.
# storageFs: Device name of the file system on the remote IBM Spectrum Scale storage cluster used for the remote mount.
addlFilesystems:
#  - name:              "fs2"
#    mountPoint:        "/mnt/fs2"
#    remoteMount:
#      storageCluster:  "storageCluster2"
#      storageFs:       "ess_fs2"

# OPTIONAL: The addlRemoteClusters section refers to additional remote IBM Spectrum Scale storage clusters (uncomment and replicate block to add more remote storage clusters).
# name: Internal name for the storageCluster definition as referred to in the addlFilesystems section above. Don't use same name as used in primaryRemoteStorageCluster above!
# host: FQDN or IP address of the GUI host for the remote IBM Spectrum Scale storage cluster.
# secretName: Name of the K8s secret that holds the IBM Spectrum Scale CNSA user credentials for this remote storage cluster.
# cacert: Name of ConfigMap containing the CA certificate of the storage cluster GUI. If not specified, the default OpenShift Container Platform CA or Red Hat CA bundle is used.
# insecureSkipVerify: To skip TLS verification, set insecureSkipVerify to true. Recommended default is false to enable TLS verification for storage cluster GUI!
# contactNodes (optional): List of contact nodes in the remote IBM Spectrum Scale storage cluster. If not specified, the operator will pick 3 nodes from the storage cluster. 
addlRemoteStorageClusters:
#  - name:                  "storageCluster2"
#    gui:  
#      host:                "my-scale-gui2.mydomain.com"
#      secretName:          "cnsa-remote-gui-secret2"
#      #cacert:             "cacert-storage-cluster-2"
#      insecureSkipVerify:  false
#    contactNodes: [storageCluster2node1, storageCluster2node2, storageCluster2node3]

## ------------------------------------
##  IBM Spectrum Scale CNSA: Call Home
## ------------------------------------
## https://www.ibm.com/docs/en/scalecontainernative?topic=operator-custom-resource

## By accepting Call Home you agree to allow IBM and its subsidiaries to store and use your contact information and your support information 
## anywhere they do business worldwide. For more information, please refer to the Program license agreement and documentation.
## For more information about call home, see https://www.ibm.com/docs/en/spectrum-scale/5.1.1?topic=overview-understanding-call-home.

# OPTIONAL: To enable IBM Call Home support, accept the license, remove the first "#" character on each line below and provide the required information.
# acceptLicense: If you agree, please respond with true for acceptance, else with false to decline (in this case call home will not be enabled)
# companyName: Name of the company to which the contact person belongs.
#              This name can consist of any alphanumeric characters and these non-alphanumeric characters: '-', '_', '.', ' ', ','.
# customerID: The IBM ID received by the customer upon purchasing a IBM Spectrum Scale license / or DEVLIC (developer edition) or TRYBUY (test edition).
#             This can consist of any alphanumeric characters and these non-alphanumeric characters: '-', '_', '.'.
# companyEmail: A group or task e-mail address to be contacted by IBM Support.
# countryCode: A two-letter uppercase country code in the ISO 3166-1 alpha-2 format (e.g. US for USA, DE for Germany).
# type: Marks the cluster as a "test" or a "production" system. In case this parameter is not explicitly set, "production" is used by default.
# If a proxy server should be used for uploads please provide the following information. Leave whole block commented out with "#" to not use a proxy. 
#   host: proxy server hostname or IP address
#   port: port of proxy server
#   secretName: Name of a basic-auth secret containg "username" and "password" for the proxy server. Leave commented out with "#" if no authentication for the proxy is required.
callHome:
  acceptLicense: false
#  companyName: "company"
#  customerID: "123456-kl"
#  companyEmail: "smith@email"
#  countryCode: "DE"
#  type: production | test
#  proxy:
#    host: "192.1.1.1"
#    port: "2345"
#    secretName: "proxy-secret"

## ---------------------------------------
##  IBM Spectrum Scale CNSA: Host Aliases
## ---------------------------------------
## https://www.ibm.com/docs/en/scalecontainernative?topic=operator-custom-resource

# OPTIONAL: hostAliases for environments where DNS cannot resolve the nodes of the remote IBM Spectrum Scale storage cluster. Uncomment and replicate list items to add more aliases.
hostAliases:
#  - hostname: "my-hostname1.mydomain.com"
#    ip: "10.11.12.101"

## ------------------------------------------------------
##  IBM Spectrum Scale CNSA: Node Selector Configuration
## ------------------------------------------------------
## https://www.ibm.com/docs/en/scalecontainernative?topic=operator-selectors-labels 

# REQUIRED: nodeSelector ensures to deploy IBM Spectrum Scale CNSA pods on nodes only matching the following node labels
# The Operator will check that a node has all labels defined present in order to deploy IBM Spectrum Scale CNSA pods on this node.
# The default below deploys IBM Spectrum Scale CNSA pods on all OpenShift "worker" nodes
nodeSelector:
  node-role.kubernetes.io/worker: ""

## ----------------------------------
##  IBM Spectrum Scale CNSA: Profile
## ----------------------------------
## https://www.ibm.com/docs/en/scalecontainernative?topic=operator-deployment-preparations

# Supported IBM Spectrum Scale configuration parameters set by default via the Operator. 
profile:
  pagepool:                           "1G"
  ignorePrefetchLUNCount:             "yes"
  workerThreads:                      1024
  maxFilesToCache:                    "128K"
  maxStatCache:                       "128K"
  maxblocksize:                       "16M"
  initPrefetchBuffers:                128
  prefetchTimeout:                    30
  prefetchPct:                        25
  prefetchMaxBuffersPerInstance:      1024
  controlSetxattrImmutableSELinux:    "yes"
  enforceFilesetQuotaOnRoot:          "yes"


####################################################
##  IBM SPECTRUM SCALE CNSA PACKAGE CONFIGURATION ##
####################################################

## -------------------------------------------
##  IBM Spectrum Scale CNSA: Container Images
## -------------------------------------------

# Scale-Core-Operator
operator:
  image:
    name: "icr.io/cpopen/ibm-spectrum-scale-operator@sha256:fe9d63c2b7733a5f8d7e1bc80e18de0160e298db14342c77aa4c6d2e26c4ee20"
    pullPolicy: Always
  loglevel:
    # zapLogLevel: Set to "info" (default) or "debug".
    zapLogLevel: info
    # zapStacktraceLevel: Set to "info" or "error" (default).
    zapStacktraceLevel: error
    # zapEncoder: Leave default. Only uncomment line below if you desire to set it to json.
    #zapEncoder: json
