# ----------------------------------------------------------------------
# Default Helm chart values for 
# IBM Spectrum Scale Container Native Storage Access v5.1.0.3
# ----------------------------------------------------------------------
# DISCLAIMER:
# These Helm charts are only intended to provide ease of use for an 
# initial deployment (helm install) of 
# IBM Spectrum Scale Container Native Storage Access (CNSA) 5.1.0.3 
# and IBM Spectrum Scale CSI driver version v2.1.0 for 
# Proof of Concepts (PoCs), demos or any other form of evaluations
# where no further lifecycle managment and upgrade paths are considered. 
# They are explicitely not intended and not suported for 
# any production use!
# These Helm charts are not supported by the 
# IBM Spectrum Scale container native nor CSI offerings 
# and are outside the scope of the IBM PMR process. 
# These Helm charts are provided on an "AS IS" BASIS, WITHOUT WARRANTIES 
# OR CONDITIONS OF ANY KIND, either express or implied, including, 
# without limitation, any warranties or conditions of TITLE, 
# NON-INFRINGEMENT, MERCHANTABILITY, or FITNESS FOR A PARTICULAR PURPOSE. 
# You are solely responsible for determining the appropriateness of 
# using or redistributing the Work and assume any risks associated with
# Your exercise of permissions under this License.
# Note, that these Helm charts do not support any lifecycle management 
# of IBM Spectrum Scale Container Native Storage Access and 
# IBM Spectrum Scale CSI driver, especially, the 
# helm upgrade|rollback|uninstall features are not supported and are not
# expected to work. 
# You need to follow the offcial IBM documentation to perform any 
# changes or upgrades to the deployment.
# ----------------------------------------------------------------------
# Deploy Helm chart into its own namespace, e.g.
# helm install <ibm-spectrum-scale> ./helm/ibm-spectrum-scale -n <ibm-spectrum-scale>
# ----------------------------------------------------------------------
# Note: In the default configuration Spectrum Scale services will be deployed on 
#       all OpenShift worker nodes (a specific nodeSelector label can be added below).
# -----------------------------------------------------------------------------------

########################################
## CUSTOMER ENVIRONMENT CONFIGURATION ##
########################################

## -----------------------------------------
##  IBM Spectrum Scale CNSA: Image Registry
## -----------------------------------------

# REQUIRED: imageRegistry as FQDN[:port] to pull the IBM Spectrum Scale CNSA images from (e.g. OpenShift internal registry: "image-registry.openshift-image-registry.svc:5000")
imageRegistry: "image-registry.openshift-image-registry.svc:5000"
# OPTIONAL: imageRegistryNamespace: Namespace used in the internal image registry; if set to "" the release namespace for the deployment will be used (e.g. ibm-spectrum-scale)
imageRegistryNamespace: ""
# OPTIONAL: imageRegistrySecret: This is the name of the imagePullSecret required for accessing an external image registry to pull images, e.g. created with: 
# kubectl create secret docker-registry [name] -n [namespace] --docker-server=[registry] --docker-username=[name] --docker-password=[password/token] --docker-email=[email]
# See https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
# imageRegistrySecret: "spectrumscale-registrykey"
imageRegistrySecret: ""

## --------------------------------------------------------
##  IBM Spectrum Scale CNSA: Primary Storage Configuration
## --------------------------------------------------------

# REQUIRED: primaryFilesystem: refers to the local file system mounted from a remote storage cluster that will also host the IBM Spectrum Scale CSI primary fileset
# name: name of the file system in the local IBM Spectrum Scale CNSA cluster (Note: "_" is not allowed as part of the local file system name)
#       IMPORTANT: the local "name" must comply with DNS label name rules, see https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#dns-label-names)
# mountPoint: mount point of the file system in the local IBM Spectrum Scale CNSA cluster; must start with "/mnt"
# storageCluster: reference to the section below in primaryRemoteStorageCluster defining the remote IBM Spectrum Scale storage cluster
# storageFs: name of the file system on the remote IBM Spectrum Scale storage cluster
primaryFilesystem:
  name:           "fs1"
  mountPoint:     "/mnt/fs1"
  storageCluster: "storageCluster1"
  storageFs:      "ess_fs1"

# REQUIRED: primaryRemoteStorageCluster: refers to the remote storage cluster that will also host the IBM Spectrum Scale CSI primary file system
# name: internally used reference to the storageCluster definition as used above in the primaryFilesystem section
# host: FQDN or IP address of the GUI host for the remote IBM Spectrum Scale storage cluster
# secretName: name of the K8s secret in the release namespace that holds the credentials for this remote storage cluster
# cacert: Name of ConfigMap containing the CA certificate of the storage cluster GUI. If not specified, the default OpenShift Container Platform CA or Red Hat CA bundle is used.
# insecureSkipVerify: To skip TLS verification, set insecureSkipVerify to true. Recommended default is "false" to enable TLS verification for storage cluster GUI!
# contactNodes (optional): list of contact nodes in the remote IBM Spectrum Scale storage cluster. If not specified, the operator will pick 3 nodes from the storage cluster. 
primaryRemoteStorageCluster:
  name:               "storageCluster1"
  gui:
    host:               "remote-scale-gui.mydomain.com"
    secretName:         "cnsa-remote-gui-secret"
    #cacert:             "cacert-storage-cluster"
    insecureSkipVerify: false
  #contactNodes: [storageCluster1node1, storageCluster1node2, storageCluster1node3]

## -----------------------------------------------------------
##  IBM Spectrum Scale CNSA: Additional Storage Configuration
## -----------------------------------------------------------

# OPTIONAL: addlFilesystems: refers to other local file systems mounted from a remote storage cluster (uncomment and replicate block to add more file systems)
# name: name of the file system in the local IBM Spectrum Scale CNSA cluster
# mountPoint: mount point of the file system in the local IBM Spectrum Scale CNSA cluster; must start with "/mnt"
# storageCluster: reference to the section below in addlRemoteStorageClusters defining the remote IBM Spectrum Scale storage cluster
# storageFs: name of the file system on the remote IBM Spectrum Scale storage cluster
addlFilesystems:
#  - name:             "fs2"
#    mountPoint:       "/mnt/fs2"
#    remoteMount:
#      storageCluster: "storageCluster2"
#      storageFs:      "ess_fs2"

# OPTIONAL: addlRemoteClusters: refers to additional remote IBM Spectrum Scale storage clusters (uncomment and replicate block to add more remote storage clusters)
# name: internally used reference to the storageCluster definition as used above in addlFilesystems section
# host: FQDN or IP address of the GUI host for the remote IBM Spectrum Scale storage cluster
# secretName: name of the K8s secret in the release namespace that holds the credentials for this remote storage cluster
# cacert: Name of ConfigMap containing the CA certificate of the storage cluster GUI. If not specified, the default OpenShift Container Platform CA or Red Hat CA bundle is used.
# insecureSkipVerify: To skip TLS verification, the insecureSkipVerify option must be set to true. 
# contactNodes (optional): list of contact nodes in the remote storage cluster. If not specified, the operator will pick 3 nodes from the storage cluster. 
addlRemoteStorageClusters:
#  - name:               "storageCluster2"
#    gui:  
#      host:               "my-scale-gui2.mydomain.com"
#      secretName:         "cnsa-remote-gui-secret2"
#      #cacert:             "cacert-storage-cluster-2"
#      insecureSkipVerify: true
#    contactNodes: [storageCluster2node1, storageCluster2node2, storageCluster2node3]

## ------------------------------------
##  IBM Spectrum Scale CNSA: Call Home
## ------------------------------------

# OPTIONAL: To enable IBM Call Home support, remove the first "#" character on each line of below "callHome:" and provide the required information
# acceptLicense: If you agree, please respond with "true" for acceptance, else with "false" to decline.
# companyName; Name of the company to which the contact person belongs.
# This name can consist of any alphanumeric characters and these non-alphanumeric characters: '-', '_', '.', ' ', ','.
# customerID: the IBM ID received by the customer upon purchasing a IBM Spectrum Scale license / or DEVLIC (developer edition) or TRYBUY (test edition)
# This can consist of any alphanumeric characters and these non-alphanumeric characters: '-', '_', '.'.
# companyEmail: a group or task e-mail address to be contacted by IBM Support
# countryCode: two-letter uppercase country code in the ISO 3166-1 alpha-2 format (e.g. US for USA, DE for Germany).
# type: Marks the cluster as a "test" or a "production" system. In case this parameter is not explicitly set, the value is set to "production" by default.
# If a proxy should be used for uploads provide the following information / otherwise leave "#" in place to not use a proxy 
#   host of proxy server as hostname or IP address
#   port of proxy server
#   secretName of a basic-auth secret, which contains username and password for proxy server
#   Leave "#" if no authentication to the proxy server is needed.
callHome:
#  acceptLicense: true
#  companyName: "company"
#  customerID: "123456-kl"
#  companyEmail: "smith@email"
#  countryCode: "de"
#  type: production | test
#  proxy:
#    host: "192.1.1.1"
#    port: "2345"
#    secretName: "proxy-secret"

## ---------------------------------------
##  IBM Spectrum Scale CNSA: Host Aliases
## ---------------------------------------

# OPTIONAL: hostAliases for environments where DNS cannot resolve the nodes of the remote IBM Spectrum Scale storage cluster. Uncomment and replicate list items to add more aliases.
hostAliases:
#  - hostname: "my-hostname1.mydomain.com"
#    ip: "10.11.12.101"

## ------------------------------------------------------
##  IBM Spectrum Scale CNSA: Node Selector Configuration
## ------------------------------------------------------

# REQUIRED: nodeSelector ensures to deploy IBM Spectrum Scale CNSA pods on nodes only matching the following node labels
# The Operator will check that a node has all labels defined present in order to deploy IBM Spectrum Scale CNSA pods on this node.
# The default below deploys IBM Spectrum Scale CNSA pods on all OpenShift "worker" nodes
nodeSelector:
  node-role.kubernetes.io/worker: ""

## ----------------------------------
##  IBM Spectrum Scale CNSA: Profile
## ----------------------------------
profile:
  pagepool:                           "1G"
  ignorePrefetchLUNCount:             "yes"
  workerThreads:                      1024
  maxFilesToCache:                    "128K"
  maxStatCache:                       "128K"
  maxblocksize:                       "16M"
  initPrefetchBuffers:                128
  prefetchTimeout:                    30
  prefetchPct:                        25
  prefetchMaxBuffersPerInstance:      1024
  controlSetxattrImmutableSELinux:    "yes"
  enforceFilesetQuotaOnRoot:          "yes"

####################################################
##  IBM SPECTRUM SCALE CNSA PACKAGE CONFIGURATION ##
####################################################

## -------------------------------------------
##  IBM Spectrum Scale CNSA: Container Images
## -------------------------------------------

# Scale-Core-Operator
operator:
  image:
    name: ibm-spectrum-scale-core-operator
    # If defined overrides the image tag which defaults to the chart appVersion in Chart.yaml
    tag: ""
    pullPolicy: Always
  loglevel:
    # zapLogLevel: can be set to "info" (default) or "debug"
    zapLogLevel: info
    # zapStacktraceLevel: can be "info or" "error" (default)
    zapStacktraceLevel: error
    # zapEncoder: can be set to json if desired (default: leave unchanged) 
    #zapEncoder: json

# Scale-Core
core:
  image:
    name: ibm-spectrum-scale-core
    # If defined overrides the image tag which defaults to the chart appVersion in Chart.yaml
    tag: ""

# Scale-Core-Init
init:
  image:
    name: ibm-spectrum-scale-core
    # If defined overrides the image tag which defaults to the chart appVersion in Chart.yaml
    tag: ""

# Scale-GUI
gui:
  image:
    name: ibm-spectrum-scale-gui
    # If defined overrides the image tag which defaults to the chart appVersion in Chart.yaml
    tag: ""

# Scale-GUI Postgres (name must include full image registry and repository path and tag if required)
postgres:
  image:
    name: "docker.io/library/postgres@sha256:a2da8071b8eba341c08577b13b41527eab3968bf1c8d28123b5b07a493a26862"

# Scale-pmCollector
collector:
  image:
    name: ibm-spectrum-scale-pmcollector
    # If defined overrides the image tag which defaults to the chart appVersion in Chart.yaml
    tag: ""

# Scale-Monitor
monitor:
  image:
    name: ibm-spectrum-scale-monitor
    # If defined overrides the image tag which defaults to the chart appVersion in Chart.yaml
    tag: ""

# Scale-Logs (name must include full image registry and repository path and tag if required)
logs:
  image:
    name: "registry.access.redhat.com/ubi8/ubi-minimal:8.3"
