apiVersion: v1
kind: Namespace
metadata:
  labels:
    app.kubernetes.io/instance: ibm-spectrum-scale
    app.kubernetes.io/name: operator
    control-plane: controller-manager
  name: ibm-spectrum-scale-operator
