apiVersion: v1
kind: Pod
metadata:
  name: ibm-spectrum-scale-test-pod
spec:
  containers:
    - name: ibm-spectrum-scale-test-pod
      image: alpine:latest
      #image: registry.access.redhat.com/ubi8/ubi-minimal:latest
      command: [ "/bin/sh", "-c", "--" ]
      args: [ "while true; do echo $(hostname) $(date +%Y%m%d-%H:%M:%S) | tee -a /data/stream1.out ; sleep 5 ; done;" ]
      volumeMounts:
        - name: vol1
          mountPath: "/data"
  volumes:
    - name: vol1
      persistentVolumeClaim:
        claimName: ibm-spectrum-scale-pvc
