apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-{{ .Values.primaryCluster.local.secret }}-test
  labels:
    helm.sh/chart: {{ include "ibm-spectrum-scale-csi.chart" . }}
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": pre-install,pre-upgrade,pre-rollback
    "helm.sh/hook-weight": "-3"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  backoffLimit: 1
  template:
    metadata:
      name: {{ .Release.Name }}-{{ .Values.primaryCluster.local.secret }}-test
    spec:
      containers:
      - name: test
        image: registry.access.redhat.com/ubi8/ubi-minimal:latest
        command: ["/bin/sh", "-c"]
        args:
        - curl -f -s -S -k -u "$(USRNAME):$(USRPWD)" https://$(GUISVR):443/scalemgmt/v2/cluster
        {{- if .Values.primarySecrets.createSecrets }}
        env:
          - name: USRNAME
            value: {{ .Values.primarySecrets.csiGuiUser.local.username }}
          - name: USRPWD
            value: {{ .Values.primarySecrets.csiGuiUser.local.password }}
        {{- else }}
        env:
          - name: USRNAME
            valueFrom:
              secretKeyRef:
                name: {{ .Values.primaryCluster.local.secret }}
                key: username
          - name: USRPWD
            valueFrom:
              secretKeyRef:
                name: {{ .Values.primaryCluster.local.secret }}
                key: password
        {{- end }}
          - name: GUISVR
            value: {{ .Values.primaryCluster.local.guiHost }}
      restartPolicy: Never
