# -----------------------------------------------------------------------
# Default Helm chart values for 
# IBM Spectrum Scale CSI driver v2.2.0
# -----------------------------------------------------------------------
# DISCLAIMER:
# These Helm charts are only intended to provide ease of use for an 
# initial deployment (helm install) of 
# IBM Spectrum Scale Container Native Storage Access (CNSA) 5.1.1.1 
# and IBM Spectrum Scale CSI driver version v2.2.0 for 
# Proof of Concepts (PoCs), demos or any other form of evaluations
# where no further lifecycle managment and upgrade paths are considered. 
# They are explicitly not intended and not suported for 
# any production use!
# These Helm charts are not supported by the 
# IBM Spectrum Scale container native nor CSI offerings 
# and are outside the scope of the IBM PMR process. 
# These Helm charts are provided on an "AS IS" BASIS, WITHOUT WARRANTIES 
# OR CONDITIONS OF ANY KIND, either express or implied, including, 
# without limitation, any warranties or conditions of TITLE, 
# NON-INFRINGEMENT, MERCHANTABILITY, or FITNESS FOR A PARTICULAR PURPOSE. 
# You are solely responsible for determining the appropriateness of 
# using or redistributing the Work and assume any risks associated with
# Your exercise of permissions under this License.
# Note, that these Helm charts do not support any lifecycle management 
# of IBM Spectrum Scale Container Native Storage Access and 
# IBM Spectrum Scale CSI driver, especially, the 
# helm upgrade|rollback|uninstall features are not supported and are not
# expected to work. 
# You need to follow the offcial IBM documentation to perform any 
# changes or upgrades to the deployment.
# ----------------------------------------------------------------------
# Deploy Helm chart into its own namespace after CNSA deployment, e.g.
# helm install ibm-spectrum-scale-csi helm/ibm-spectrum-scale-csi \
#      --set primaryCluster.local.clusterId="$CLUSTERID" \
#      -n ibm-spectrum-scale-csi-driver
# with
#   ibm-spectrum-scale-csi: Helm release name of the deployment, can be freely chosen
#   helm/ibm-spectrum-scale-csi: Helm chart of IBM Spectrum Scale CSI driver
#   -n ibm-spectrum-scale-csi-driver: Namespace of the deployment
# ----------------------------------------------------------------------
# From local IBM Spectrum Scale CNSA cluster, obtain:
# CLUSTERID=$(oc exec $(oc get pods|grep "core"|tail -1|cut -d' ' -f1) -- mmlscluster -Y|grep clusterSummary|tail -1|cut -d':' -f8)
# ----------------------------------------------------------------------
# Note: In the default configuration all OpenShift worker nodes
#       to run IBM Spectrum Scale CSI services need to be labeled 
#       with "scale=true" (the label can be customized below).
# ----------------------------------------------------------------------

########################################
## CUSTOMER ENVIRONMENT CONFIGURATION ##
########################################

## ----------------------------------------------
##  IBM Spectrum Scale CSI: Driver Configuration
## ----------------------------------------------

# OPTIONAL: csiNamespace is the namespace to deploy CSI driver in. If undefined ("") the release namespace of the Helm chart will be used for CSI driver.
csiNamespace: ""

## -------------------------------------------
##  IBM Spectrum Scale: Credentials & Secrets
## -------------------------------------------

# OPTIONAL: The secrets must either have been created manually prior to installation (recommended - in this case skip this section) 
#           or can be created through the Helm chart by setting createSecrets to true and providing all required credentials
#           in the section below.
# Note: Having plain text passwords in this config file is _not_ considered best practice for security reasons and therefore not recommended!
primarySecrets:
  # No secrets will be created through the Helm chart if createSecrets is set to false (default)!
  createSecrets: false
  csiGuiUser:
    # IBM Spectrum Scale CSI driver user credentials on local compute/CNSA cluster GUI (csi-local-secret)
    local:
      username: "csi_admin1"
      password: "csi_PASSWORD1"
    # IBM Spectrum Scale CSI driver user credentials on remote storage cluster GUI (csi-remote-secret)
    remote:
      username: "csi_admin2"
      password: "csi_PASSWORD2"

## -----------------------------------------------------------
##  IBM Spectrum Scale CSI: Primary File System Configuration
## -----------------------------------------------------------

# REQUIRED: primaryCluster is the local IBM Spectrum Scale CNSA cluster that will mount the primary file system and store IBM Spectrum Scale CSI driver configuration data.
primaryCluster:
  # REQUIRED: primaryFs is the primary file system for IBM Spectrum Scale CSI driver to store its config data. CNSA configuration will be applied here automatically. 
  primaryFs:              "fs1"
  # OPTIONAL: primaryFset is the IBM Spectrum Scale CSI driver fileset name. Set to "" for the default: "spectrum-scale-csi-volume-store".
  # OPTIONAL: primaryFsetInodeLimit sets the inode limit on the IBM Spectrum Scale CSI driver fileset. Set to "" for using defaults.
  primaryFset:            ""
  primaryFsetInodeLimit:  ""
  local:
    # REQUIRED: clusterId is the Cluster ID of the local IBM Spectrum Scale CNSA cluster (will be specified with helm install --set primaryCluster.local.clusterId="$CLUSTERID").
    # REQUIRED: guiHost is the Kubernetes service name of local IBM Spectrum Scale CNSA GUI service composed of "ibm-spectrum-scale-gui.<CNSA-namespace>".
    # REQUIRED: secret is name of the Kubernetes secret with username/password for the CSI driver user to access the GUI on the local IBM Spectrum Scale CNSA cluster.
    clusterId:  "needs-to-be-read-after-CNSA-deployment"   
    guiHost:    "ibm-spectrum-scale-gui.<replace-with-CNSA-namespace>"
    secret:     "csi-local-secret"
    # OPTIONAL: secureSslMode can be set to true or false. Default is false. If set to true cacert must be configured! 
    # OPTIONAL: cacert is the name of CA certificate configmap for accessing the GUI of the local IBM Spectrum Scale CNSA cluster. It is ignored if set to "".
    secureSslMode: false
    cacert:        ""
  remote:
    # REQUIRED: clusterId is the cluster ID of the remote IBM Spectrum Scale storage cluster if primaryFs is a remotely mounted file system from a remote storage cluster.
    # REQUIRED: secret is the name of the Kubernetes secret with username/password for CSI driver user to access the GUI on the remote IBM Spectrum Scale storage cluster.
    # REQUIRED: guiHost is the FQDN or IP address of the GUI host for the remote IBM Spectrum Scale storage cluster. CNSA configuration will be applied here automatically.
    clusterId:  "215057217487177715"
    secret:     "csi-remote-secret"
    guiHost:    "my-scale-gui.mydomain.com"
    # OPTIONAL: secureSslMode can be set to true or false. Default is false. If set to true cacert must be configured! 
    # OPTIONAL: cacert is the name of CA certificate configmap for accessing the GUI of the remote IBM Spectrum Scale storage cluster. It is ignored if set to "".
    secureSslMode:   false
    cacert:          ""

## -----------------------------------------------------------------------------------------
##  IBM Spectrum Scale CSI: Additional Remotely Mounted IBM Spectrum Scale Storage Clusters 
## -----------------------------------------------------------------------------------------
## https://www.ibm.com/docs/en/spectrum-scale-csi?topic=operator-remote-cluster-support

# OPTIONAL: Cluster ID(s) of additional remote IBM Spectrum Scale storage cluster(s). Uncomment and replicate section to add more clusters.
# Note: If you add additional remote IBM Spectrum Scale storage clusters in the addlRemoteStorageClusters section for CNSA you also need to add them here for CSI.
addlRemoteClusters:
#  - id:                 "Remote Storage Cluster #2 ID"
#    secrets:            "csi-remote-secret2"
#    restApi:
#      - guiHost:        "remote-gui-host2"
#    secureSslMode:      false
#    cacert:             ""

## -----------------------------------------------------
##  IBM Spectrum Scale CSI: Node Selector Configuration
## -----------------------------------------------------
## https://www.ibm.com/docs/en/spectrum-scale-csi?topic=operator-using-node-selector

# The IBM Spectrum Scale CSI Operator will check that a node has all the labels defined below in order to deploy IBM Spectrum Scale CSI pods on this node.
# REQUIRED: csiNodeSelectorBase "scale: true" is the default node label for deploying IBM Spectrum Scale CSI pods on a node. Leave as is for the default.
csiNodeSelectorBase:
  key:    "scale"
  value:  "true"
# OPTIONAL: csiNodeSelectorProvisioner is an additional node label to run the IBM Spectrum Scale CSI Provisioner pods
# on a specifc subset of CSI nodes (highly reliable OpenShift infrastructure nodes), e.g. key: "infranode", value: "1".
# Set only if required. Otherwise set key: "" to be ignored.
csiNodeSelectorProvisioner:
  key:    ""
  value:  ""
# OPTIONAL: csiNodeSelectorAttacher is an additional node label to run the IBM Spectrum Scale CSI Attacher pods
# on a specifc subset of CSI nodes (highly reliable OpenShift infrastructure nodes), e.g. key: "infranode", value: "2".
# Set only if required. Otherwise set key: "" to be ignored.
csiNodeSelectorAttacher:
  key:    ""
  value:  ""
# OPTIONAL: csiNodeSelectorSnapshotter is an additional node label to run the IBM Spectrum Scale CSI Snapshotter pods
# on a specifc subset of CSI nodes (highly reliable OpenShift infrastructure nodes), e.g. key: "infranode", value: "3".
# Set only if required. Otherwise set key: "" to be ignored.
csiNodeSelectorSnapshotter:
  key:    ""
  value:  ""

## ---------------------------------------------------
##  IBM Spectrum Scale CSI: Tolerations Configuration
## ---------------------------------------------------
## https://www.ibm.com/docs/en/spectrum-scale-csi?topic=operator-tolerations

# OPTIONAL: csiTolerations is an array of Kubernetes tolerations distribued to IBM Spectrum Scale CSI pods.
# https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/
csiTolerations:
#  - key: "key1"
#    operator: "Equal"
#    value: "value1"
#    effect: "NoExecute"
#    tolerationSeconds: 3600
#  - key: "key2"
#    operator: "Equal"
#    value: "value1"
#    effect: "NoExecute"
#    tolerationSeconds: 3600

## --------------------------------------
##  IBM Spectrum Scale CSI: Node Mapping
## --------------------------------------
# https://www.ibm.com/docs/en/spectrum-scale-csi?topic=operator-kubernetes-spectrum-scale-node-mapping

# OPTIONAL: csiNodeMapping is an array of node mappings in case K8s node names (oc get nodes) differ from SpectrumScale node names (mmlscluster).
# In case a K8s node name starts with a number (e.g. "198.51.100.10") then use "K8sNodePrefix_< K8s Node Name >" 
# as format for the k8sNode name (e.g. "K8sNodePrefix_198.51.100.10")
csiNodeMapping:
#  - k8sNode: "< K8s Node Name >"
#    spectrumscaleNode: "< SpectrumScale Node Name >"
#  - k8sNode: "< K8s Node Name >"
#    spectrumscaleNode: "< SpectrumScale Node Name >"
#  - k8sNode: "K8sNodePrefix_< K8s Node Name >"
#    spectrumscaleNode: "< SpectrumScale Node Name >"
#  - k8sNode: "K8sNodePrefix_< K8s Node Name >"
#    spectrumscaleNode: "< SpectrumScale Node Name >"


##########################################################
## IBM SPECTRUM SCALE CSI PACKAGE DEFAULT CONFIGURATION ##
##########################################################

## ----------------------------------------
##  IBM Spectrum Scale CSI Product Version
## ----------------------------------------
csiProductVersion: 2.2.0

## ----------------------------------------------------
##  IBM Spectrum Scale CSI Kubelet root directory path
## ----------------------------------------------------

# OPTIONAL: csiKubeletRootDirPath is the Kubelet root directory path, in case we don't want to use the default kubelet root directory path.
# Default values are used if set to "" (i.e. "/var/lib/kubelet"). 
csiKubeletRootDirPath: ""

## -----------------------------------------------
##  IBM Spectrum Scale CSI Image Registry Secrets
## -----------------------------------------------

# OPTIONAL: csiImagePullSecrets is a list of imagePullSecrets names that may be required for accessing an external image registry to pull images, e.g. created with: 
# kubectl create secret docker-registry [name] -n [namespace] --docker-server=[registry] --docker-username=[name] --docker-password=[password/token] --docker-email=[email]
# See https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry for more information.
csiImagePullSecrets:
#    - myImagePullSecretName01
#    - myImagePullSecretName02

## -------------------------------
##  IBM Spectrum Scale CSI Images
## -------------------------------

# Please specify the full image registry path including repository/namespace in the image names below. Required imagePullSecrets can be defined above. 

csiOperator:
  image:
    # Scale CSI Operator image name (including full image registry path) and tag, e.g. "quay.io/ibm-spectrum-scale/ibm-spectrum-scale-csi-operator:v2.2.0"
    # If tag is set to "" it defaults to the chart appVersion defined in Chart.yaml.
    name: "quay.io/ibm-spectrum-scale/ibm-spectrum-scale-csi-operator"
    tag:  ""

csiDriver:
  image:
    # Scale CSI Driver image name (including full image registry path) and tag in case we do need to override the default image,
    # e.g. "quay.io/ibm-spectrum-scale/ibm-spectrum-scale-csi-driver:v2.2.0". Default values are used if name is set to "". 
    name: ""
    tag:  "v2.2.0"

csiAttacher:
  image:
    # Attacher image name (including full image registry path) and tag in case we do need to override the default image,
    # e.g. "us.gcr.io/k8s-artifacts-prod/sig-storage/csi-attacher:v3.1.0". Default values are used if name is set to "". 
    name: ""
    tag:  "v3.1.0"

csiProvisioner:
  image:
    # Provisioner image name (including full image registry path) and tag in case we do need to override the default image,
    # e.g. "us.gcr.io/k8s-artifacts-prod/sig-storage/csi-provisioner:v2.1.0". Default values are used if name is set to "".
    name: ""
    tag:  "v2.1.0"

csiDriverRegistrar:
  image:
    # Driver Registrar image name (including full image registry path) and tag in case we do need to override the default image,
    # e.g. "us.gcr.io/k8s-artifacts-prod/sig-storage/csi-node-driver-registrar:v2.1.0". Default values are used if name is set to "".
    name: ""
    tag:  "v2.1.0"

csiSnapshotter:
  image:
    # Snapshotter image name (including full image registry path) and tag in case we do need to override the default image,
    # e.g. "us.gcr.io/k8s-artifacts-prod/sig-storage/csi-snapshotter:v4.0.0". Default values are used if name is set to "".
    name: ""
    tag:  "v4.0.0"

## -------------------------------------------------------------------------
##  IBM Spectrum Scale CNSA Variables for combinded deployment (CNSA & CSI)
## -------------------------------------------------------------------------

# These variables are defined as empty variables. They will be populated accordingly when used in conjunction with 
# the IBM Spectrum Scale Container Native Storage Access (CNSA) Helm chart deployment.
primaryFilesystem:
  name:           ""
primaryRemoteStorageCluster:
  gui:
    host:  ""
