# -----------------------------------------------------------------------
# Default Helm chart values for 
# IBM Spectrum Scale CSI driver v2.1.0
# -----------------------------------------------------------------------
# DISCLAIMER:
# These Helm charts are only intended to provide ease of use for an 
# initial deployment (helm install) of 
# IBM Spectrum Scale Container Native Storage Access (CNSA) 5.1.0.3 
# and IBM Spectrum Scale CSI driver version v2.1.0 for 
# Proof of Concepts (PoCs), demos or any other form of evaluations
# where no further lifecycle managment and upgrade paths are considered. 
# They are explicitely not intended and not suported for 
# any production use!
# These Helm charts are not supported by the 
# IBM Spectrum Scale container native nor CSI offerings 
# and are outside the scope of the IBM PMR process. 
# These Helm charts are provided on an "AS IS" BASIS, WITHOUT WARRANTIES 
# OR CONDITIONS OF ANY KIND, either express or implied, including, 
# without limitation, any warranties or conditions of TITLE, 
# NON-INFRINGEMENT, MERCHANTABILITY, or FITNESS FOR A PARTICULAR PURPOSE. 
# You are solely responsible for determining the appropriateness of 
# using or redistributing the Work and assume any risks associated with
# Your exercise of permissions under this License.
# Note, that these Helm charts do not support any lifecycle management 
# of IBM Spectrum Scale Container Native Storage Access and 
# IBM Spectrum Scale CSI driver, especially, the 
# helm upgrade|rollback|uninstall features are not supported and are not
# expected to work. 
# You need to follow the offcial IBM documentation to perform any 
# changes or upgrades to the deployment.
# ----------------------------------------------------------------------
# Deploy Helm chart into its own namespace after CNSA deployment, e.g.
# helm install <ibm-spectrum-scale-csi> ./helm/ibm-spectrum-scale-csi \
#      --set primaryCluster.localClusterId="$CLUSTERID" \
#      -n <ibm-spectrum-scale-csi-driver>
# ----------------------------------------------------------------------
# From local IBM Spectrum Scale CNSA cluster, obtain:
# CLUSTERID=$(oc exec $(oc get pods|grep "core"|tail -1|cut -d' ' -f1) -- mmlscluster -Y|grep clusterSummary|tail -1|cut -d':' -f8)
# ----------------------------------------------------------------------
# Note: In the default configuration all OpenShift worker nodes
#       to run IBM Spectrum Scale CSI services need to be labeled 
#       with "scale=true" (the label can be customized below).
# ----------------------------------------------------------------------

########################################
## CUSTOMER ENVIRONMENT CONFIGURATION ##
########################################

## ----------------------------------------------
##  IBM Spectrum Scale CSI: Driver Configuration
## ----------------------------------------------

# OPTIONAL: namespace: csiNamespace to depoy CSI. If undefined ("") the release namespace of the Helm chart will be used as default for CSI
csiNamespace:          ""
# REQUIRED: scaleHostpath: Mount path of the primary file system (primaryFs) on the local IBM Spectrum Scale API host
scaleHostpath:         "/mnt/fs1"

## -----------------------------------------------------------
##  IBM Spectrum Scale CSI: Primary File System Configuration
## -----------------------------------------------------------

# REQUIRED: primaryCluster: local IBM Spectrum Scale CNSA cluster that will also mount the primary file system to store IBM Spectrum Scale CSI configuration data
primaryCluster:
  # REQUIRED: localClusterId: Cluster ID of the local IBM Spectrum Scale CNSA cluster (will be specified with helm install --set primaryCluster.localClusterId="$CLUSTERID")
  # REQUIRED: localGuiHost: Kubernetes service name of local IBM Spectrum Scale CNSA GUI
  # REQUIRED: localCsiSecret: Kubernetes secret with username/password for csi-user in the GUI of the local IBM Spectrum Scale CNSA cluster
  # OPTIONAL: localSecureSslMode: true/false
  # OPTIONAL: localCAcert: Name of CA cert configmap for the GUI of the local IBM Spectrum Scale CNSA cluster
  localClusterId:         "needs-to-be-read-after-CNSA-deployment"   
  localGuiHost:           "ibm-spectrum-scale-gui.<replace-with-CNSA-namespace>"
  localCsiSecret:         "csi-local-secret"
  localSecureSslMode:     false
  localCAcert:            ""
  # REQUIRED: primaryFs: Primary file system for IBM Spectrum Scale CSI Driver to store its config data / CNSA configuration will be applied here automatically 
  # OPTIONAL: primaryFset: Leave empty as "" for default IBM Spectrum Scale CSI fileset name which is "spectrum-scale-csi-volume-store"
  # OPTIONAL: primaryFsetInodeLimit: Leave empty as "" for using defaults for the IBM Spectrum Scale CSI fileset
  primaryFs:              "fs1"
  primaryFset:            ""
  primaryFsetInodeLimit:  ""
  # REQUIRED: primaryRemoteClusterId: Cluster ID of the remote IBM Spectrum Scale storage cluster if primaryFs is a remote cluster file system
  # REQUIRED: primaryRemoteCsiSecret: Name of the K8s secret with username/password for CSI to access the GUI on the remote IBM Spectrum Scale storage cluster
  # REQUIRED: primaryRemoteGuiHost: FQDN or IP address of the GUI host for the remote IBM Spectrum Scale storage cluster / CNSA configuration will be applied here automatically 
  # OPTIONAL: primaryRemoteSecureSslMode: true/false
  # OPTIONAL: primaryRemoteCAcert: Name of CA cert configmap for accessing the GUI of the remote IBM Spectrum Scale storage cluster
  primaryRemoteClusterId:       "2303539379337927823"
  primaryRemoteCsiSecret:       "csi-remote-secret"
  primaryRemoteSecureSslMode:   false
  primaryRemoteCAcert:          ""
  primaryRemoteGuiHost:         "my-scale-gui.mydomain.com"

## -----------------------------------------------------------------------------------------
##  IBM Spectrum Scale CSI: Additional Remotely Mounted IBM Spectrum Scale Storage Clusters 
## -----------------------------------------------------------------------------------------

# OPTIONAL: Cluster ID(s) of additional remote IBM Spectrum Scale storage cluster(s) / uncomment and replicate section to add more clusters
# Note: If you add additional remote IBM Spectrum Scale storage clusters in section "addlRemoteStorageClusters:" for CNSA you also need to add them here for CSI.
addlRemoteClusters:
#  - id:                 "Remote Storage Cluster #2 ID"
#    secrets:            "csi-remote-secret2"
#    restApi:
#      - guiHost:        "remote-gui-host2"
#    secureSslMode:      false
#    cacert:             ""

## -----------------------------------------------------
##  IBM Spectrum Scale CSI: Node Selector Configuration
## -----------------------------------------------------

# The IBM Spectrum Scale CSI Operator will check that a node has all the labels defined below in order to deploy IBM Spectrum Scale CSI pods on this node.
# REQUIRED: csiNodeSelectorBase "scale: true" is the default node label for deploying Spectrum Scale CSI pods on a node (DEFAULT / leave as is)
csiNodeSelectorBase:
  key:    "scale"
  value:  "true"
# OPTIONAL: csiNodeSelectorProvisioner is an additional node label to run the IBM Spectrum Scale CSI Provisioner pods
# on a specifc subset of CSI nodes (highly reliable OpenShift infrastructure nodes), e.g. key: "infranode", value: "1"
# Set only if required. Otherwise set key: "" to be ignored.
csiNodeSelectorProvisioner:
  key:    ""
  value:  ""
# OPTIONAL: csiNodeSelectorAttacher is an additional node label to run the IBM Spectrum Scale CSI Attacher pods
# on a specifc subset of CSI nodes (highly reliable OpenShift infrastructure nodes), e.g. key: "infranode", value: "2"
# Set only if required. Otherwise set key: "" to be ignored.
csiNodeSelectorAttacher:
  key:    ""
  value:  ""

## ---------------------------------------------------
##  IBM Spectrum Scale CSI: Tolerations Configuration
## ---------------------------------------------------
# https://www.ibm.com/docs/en/spectrum-scale-csi?topic=operator-tolerations

# OPTIONAL: csiTolerations is an array of Kubernetes tolerations distribued to IBM Spectrum Scale CSI pods
# https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/
csiTolerations:
#  - key: "key1"
#    operator: "Equal"
#    value: "value1"
#    effect: "NoExecute"
#    tolerationSeconds: 3600
#  - key: "key2"
#    operator: "Equal"
#    value: "value1"
#    effect: "NoExecute"
#    tolerationSeconds: 3600

##########################################################
## IBM SPECTRUM SCALE CSI PACKAGE DEFAULT CONFIGURATION ##
##########################################################

## ----------------------------------------
##  IBM Spectrum Scale CSI Product Version
## ----------------------------------------
csiProductVersion: 2.1.0

## -----------------------------------------------
##  IBM Spectrum Scale CSI Image Registry Secrets
## -----------------------------------------------

# OPTIONAL: csiImagePullSecrets is a list of imagePullSecrets that may be required for accessing an external image registry to pull images, e.g. created with: 
# kubectl create secret docker-registry [name] -n [namespace] --docker-server=[registry] --docker-username=[name] --docker-password=[password/token] --docker-email=[email]
# See https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
csiImagePullSecrets:
#    - myImagePullSecretName01
#    - myImagePullSecretName02

## -------------------------------
##  IBM Spectrum Scale CSI Images
## -------------------------------

# Please specify the full image registry path including repository/namespace in the image names below. Required imagePullSecrets can be defined above. 

csiOperator:
  image:
    # Scale CSI Operator image name (including full image registry path) and tag, e.g. "quay.io/ibm-spectrum-scale/ibm-spectrum-scale-csi-operator:v2.1.0"
    # If tag is set to tag: "" it defaults to the chart appVersion defined in Chart.yaml.
    name: "quay.io/ibm-spectrum-scale/ibm-spectrum-scale-csi-operator"
    tag:  ""

csiDriver:
  image:
    # Scale CSI Driver image name (including full image registry path) and tag, e.g. "quay.io/ibm-spectrum-scale/ibm-spectrum-scale-csi-driver:v2.1.0"
    # If tag is set to tag: "" it defaults to the chart appVersion defined in Chart.yaml.
    name: "quay.io/ibm-spectrum-scale/ibm-spectrum-scale-csi-driver"
    tag:  ""

csiAttacher:
  image:
    # Attacher image name (including full image registry path) and tag in case we do need to override the default image (required for System p and System z),
    # e.g. "us.gcr.io/k8s-artifacts-prod/sig-storage/csi-attacher:v3.0.0". Default values are used if name is set to name: "". 
    name: ""
    tag:  "v3.0.0"

csiProvisioner:
  image:
    # Provisioner image name (including full image registry path) and tag in case we do need to override the default image (required for System p and System z),
    # e.g. "us.gcr.io/k8s-artifacts-prod/sig-storage/csi-provisioner:v2.0.2". Default values are used if name is set to name: "".
    name: ""
    tag:  "v2.0.2"

csiDriverRegistrar:
  image:
    # Driver Registrar image name (including full image registry path) and tag in case we do need to override the default image (required for System p and System z),
    # e.g. "us.gcr.io/k8s-artifacts-prod/sig-storage/csi-node-driver-registrar:v2.0.1". Default values are used if name is set to name: "".
    name: ""
    tag:  "v2.0.1"

## -------------------------------------------------------------------------
##  IBM Spectrum Scale CNSA Variables for combinded deployment (CNSA & CSI)
## -------------------------------------------------------------------------

# These variables are defined as empty variables. They will be populated accordingly when used in conjunction with 
# the IBM Spectrum Scale Container Native Storage Access (CNSA) Helm chart deployment.
primaryFilesystem:
  name:           ""
  mountPoint:     ""
primaryRemoteStorageCluster:
  gui:
    host:  ""
