{{- if .Values.primarySecrets.createSecrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.primaryRemoteStorageCluster.gui.secretName }}
data:
  username: {{ .Values.primarySecrets.cnsaGuiUser.remote.username | b64enc }}
  password: {{ .Values.primarySecrets.cnsaGuiUser.remote.password | b64enc }}
type: Opaque
{{- end }}
