{{- if .Values.createSecrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.remoteCluster.gui.secretName }}
  namespace: ibm-spectrum-scale
data:
  username: {{ .Values.cnsaGuiUser.username | b64enc }}
  password: {{ .Values.cnsaGuiUser.password | b64enc }}
type: Opaque
{{- end }}
