{{- if .Values.createSecrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.remoteCluster.gui.csiSecretName }}
  namespace: ibm-spectrum-scale-csi
  labels:
    product: ibm-spectrum-scale-csi
data:
  username: {{ .Values.csiGuiUser.username | b64enc }}
  password: {{ .Values.csiGuiUser.password | b64enc }}
type: Opaque
{{- end }}
