apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: ibm-spectrum-scale
    app.kubernetes.io/name: operator
    control-plane: controller-manager
  name: ibm-spectrum-scale-controller-manager
  namespace: ibm-spectrum-scale-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: ibm-spectrum-scale
      app.kubernetes.io/name: operator
      control-plane: controller-manager
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: ibm-spectrum-scale
        app.kubernetes.io/name: operator
        control-plane: controller-manager
    spec:
      containers:
      - args:
        - --config=controller_manager_config.yaml
        - --zap-log-level=1
        command:
        - /manager
        image: {{ .Values.cnsaImages.operator }}
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        name: manager
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        securityContext:
          allowPrivilegeEscalation: false
        volumeMounts:
        - mountPath: /controller_manager_config.yaml
          name: manager-config
          subPath: controller_manager_config.yaml
        - mountPath: /etc/ssl/service
          name: cabundle
      serviceAccountName: ibm-spectrum-scale-operator
      terminationGracePeriodSeconds: 10
      volumes:
      - configMap:
          name: ibm-spectrum-scale-manager-config
        name: manager-config
      - configMap:
          name: ibm-spectrum-scale-cabundle
          optional: true
        name: cabundle
