apiVersion: scale.spectrum.ibm.com/v1beta1
kind: Filesystem
metadata:
  labels:
    app.kubernetes.io/instance: ibm-spectrum-scale
    app.kubernetes.io/name: cluster
  name: {{ .Values.primaryFilesystem.localFs }}
  namespace: ibm-spectrum-scale
spec:
  remote:
    cluster: {{ .Values.primaryFilesystem.remoteCluster }}
    fs: {{ .Values.primaryFilesystem.remoteFs }}
