apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-cnsa-gui-access-test
  namespace: ibm-spectrum-scale
  labels:
    helm.sh/chart: {{ include "ibm-spectrum-scale.chart" . }}
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": pre-install,pre-upgrade,pre-rollback
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  backoffLimit: 1
  template:
    metadata:
      name: {{ .Release.Name }}-{{ .Values.remoteCluster.gui.secretName }}-test
    spec:
      {{- if .Values.daemon.hostAliases }}
      hostAliases:
        {{- toYaml .Values.daemon.hostAliases | nindent 6 | replace "hostname:" "hostnames:\n        -" }}
      {{- end }}
      containers:
      - name: test
        image: registry.access.redhat.com/ubi8/ubi-minimal:latest
        command: ["/bin/sh", "-c"]
        args:
        - curl -f -s -S -k -u "$(USRNAME):$(USRPWD)" https://$(GUISVR):443/scalemgmt/v2/cluster
        {{- if .Values.createSecrets }}
        env:
          - name: USRNAME
            value: {{ .Values.cnsaGuiUser.username }}
          - name: USRPWD
            value: {{ .Values.cnsaGuiUser.password }}
        {{- else }}
        env:
          - name: USRNAME
            valueFrom:
              secretKeyRef:
                name: {{ .Values.remoteCluster.gui.secretName }}          
                key: username
          - name: USRPWD
            valueFrom:
              secretKeyRef:
                name: {{ .Values.remoteCluster.gui.secretName }}          
                key: password
        {{- end }}
          - name: GUISVR
            value: {{ .Values.remoteCluster.gui.host }}
      restartPolicy: Never
      