# NOTE: Applying changes to the CR after the cluster has been created will
# not trigger an update of the running pods. To update a pod that is
# currently running, the pod will need to be manually deleted. When the pod is
# recreated, the updates will be applied.
apiVersion: scale.ibm.com/v1
kind: ScaleCluster
metadata:
  name: ibm-spectrum-scale
  labels:
    helm.sh/chart: {{ include "ibm-spectrum-scale.chart" . }}
spec:
  # -------------------------------------------------------------------------------
  # nodeSelector is a User Configurable field.
  # -------------------------------------------------------------------------------
  # In conjunction with the nodeSelector configuration, the operator also
  # applies node affinity according to supported architectures and OS.
  # More info on node selectors:
  #       https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#nodeselector
  # note: changing this field after first deployment may require manual pod deletions.
  # Deploy pods on nodes matching the following node labels:
  nodeSelector:
    {{- toYaml .Values.nodeSelector | nindent 4 }}

  # -------------------------------------------------------------------------------
  # license acceptance for IBM Spectrum Scale is a required field 
  # -------------------------------------------------------------------------------
  # User must accept the Spectrum Scale license to deploy a CNSA cluster.
  # By specifying "accept: true" below, user agrees to the terms and conditions set
  # forth by the IBM Spectrum Scale Container Native Data Access/Data Management license located
  # at https://www14.software.ibm.com/cgi-bin/weblap/lap.pl?l=en&popup=y&li_formnum=L-CPES-C3MSKL&title=IBM%20License%20Agreement
  #
  # Enter either data-access or data-management to the license.license field. Customers entitled to
  # the Data Management Edition can use either data-management or data-access. Customers entitled to
  # the Data Access Edition can only use data-access.
  # -------------------------------------------------------------------------------
  license:
    accept: {{ .Values.license.accept | default false }}
    license: {{ .Values.license.license | default "data-access" }}

  # -------------------------------------------------------------------------------
  # call home functionality is optional
  # -------------------------------------------------------------------------------
  # # TO ENABLE: Remove the first # character on each line of this section to configure and enable call home
  # callhome:
  #   # By accepting this request, you agree to allow IBM and its subsidiaries to store and use your contact information and your support information anywhere they do business worldwide. For more information, please refer to the Program license agreement and documentation.
  #   # If you agree, please respond with "true" for acceptance, else with "false" to decline.
  #   acceptLicense: true | false
  #   # companyName of the company to which the contact person belongs.
  #   # This name can consist of any alphanumeric characters and these non-alphanumeric characters: '-', '_', '.', ' ', ','.
  #   companyName:
  #   # customerID of the system administrator who can be contacted by the IBM Support.
  #   # This can consist of any alphanumeric characters and these non-alphanumeric characters: '-', '_', '.'.
  #   customerID: ""
  #   # companyEmail address of the system administrator who can be contacted by the IBM Support.
  #   # Usually this e-mail address is directed towards a group or task e-mail address. For example, itsupport@mycompanyname.com.
  #   companyEmail:
  #   # countryCode two-letter upper-case country codes as defined in ISO 3166-1 alpha-2.
  #   countryCode:
  #   # Marks the cluster as a "test" or a "production" system. In case this parameter is not explicitly set, the value is set to "production" by default.
  #   type: production | test
  #   # Remove or leave the proxy block commented if a proxy should not be used for uploads
  #   proxy:
  #     # host of proxy server as hostname or IP address
  #     host:
  #     # port of proxy server
  #     port:
  #     # secretName of a basic-auth secret, which contains username and password for proxy server
  #     # Remove the secretName if no authentication to the proxy server is needed.
  #     secretName:
  {{- if .Values.callHome.acceptLicense }}
  callhome:
    {{- toYaml .Values.callHome | nindent 4 }}
  {{- end }}

  # -------------------------------------------------------------------------------
  # filesystems block is required for Remote Mount
  # -------------------------------------------------------------------------------
  # filesystems[name].remoteMount.storageCluster refers to the name of a remoteCluster defined in the proceeding block
  # note: adding, removing, or updating a filesystem name or mountPoint after first deployment will require manual pod deletions.
  filesystems:
    - name: "{{ .Values.primaryFilesystem.name }}"
      remoteMount:
        storageCluster: "{{ .Values.primaryFilesystem.storageCluster }}"
        storageFs: "{{ .Values.primaryFilesystem.storageFs }}"
      # mountPoint must start with `/mnt`
      mountPoint: "{{ .Values.primaryFilesystem.mountPoint }}"
    {{- if .Values.addlFilesystems }}
      {{- toYaml .Values.addlFilesystems | nindent 4 }}
    {{- end }}

  # -------------------------------------------------------------------------------
  # The remoteClusters field is required for remote mount
  # -------------------------------------------------------------------------------
  # A remoteCluster definition provides the name, hostname, its GUI secret, and contact node.
  # The remoteCluster name is referenced in the filesystems[name].remoteMount.storageCluster
  # used for Remote Mount
  remoteClusters:
    - name: "{{ .Values.primaryRemoteStorageCluster.name }}"
      gui:
        host: "{{ .Values.primaryRemoteStorageCluster.gui.host }}"
        secretName: "{{ .Values.primaryRemoteStorageCluster.gui.secretName }}"
        {{- if .Values.primaryRemoteStorageCluster.gui.cacert }}
        cacert: {{ .Values.primaryRemoteStorageCluster.gui.cacert }}
        {{- end }}
        insecureSkipVerify: {{ .Values.primaryRemoteStorageCluster.gui.insecureSkipVerify }}
      {{- if .Values.primaryRemoteStorageCluster.contactNodes }}
      contactNodes:
        {{- toYaml .Values.primaryRemoteStorageCluster.contactNodes | nindent 8 }}
      {{- end }}
    {{- if .Values.addlRemoteStorageClusters }}
      {{- toYaml .Values.addlRemoteStorageClusters | nindent 4 }}
    {{- end }}

  # -------------------------------------------------------------------------------
  # hostAliases is optional
  # -------------------------------------------------------------------------------
  # hostAliases is used in an environment where DNS cannot resolve the remote (storage) cluster
  # note: changing this field after first deployment will require manual pod deletions.
  # hostAliases:
  #   - hostname: example.com
  #     ip: 10.0.0.1
  {{- if .Values.hostAliases }}
  hostAliases:
    {{- toYaml .Values.hostAliases | nindent 4 }}
  {{- end }}
  
