apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: ibm-spectrum-scale-operator
    app.kubernetes.io/managed-by: ibm-spectrum-scale-operator
    app.kubernetes.io/name: ibm-spectrum-scale-operator
    product: ibm-spectrum-scale-core
    release: ibm-spectrum-scale-operator
    helm.sh/chart: {{ include "ibm-spectrum-scale.chart" . }}
  name: ibm-spectrum-scale-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: ibm-spectrum-scale-operator
  template:
    metadata:
      labels:
        name: ibm-spectrum-scale-operator
        app.kubernetes.io/instance: ibm-spectrum-scale-operator
        app.kubernetes.io/managed-by: ibm-spectrum-scale-operator
        app.kubernetes.io/name: ibm-spectrum-scale-operator
    spec:
      serviceAccountName: ibm-spectrum-scale-operator
      hostIPC: false
      hostNetwork: false
      hostPID: false
      containers:
        - name: operator
          command:
            - /manager
          args:
            - --enable-leader-election
            # Log level can be set to info or debug
            - --zap-log-level={{ .Values.operator.loglevel.zapLogLevel }}
            # Stacktrace level can be info or error
            - --zap-stacktrace-level={{ .Values.operator.loglevel.zapStacktraceLevel }}
            # Encoder can be set to json if desired
            # - --zap-encoder=json
            {{- if .Values.operator.loglevel.zapEncoder }}
            - --zap-encoder={{ .Values.operator.loglevel.zapEncoder }}
            {{- end }}
          image: {{ .Values.operator.image.name }}
          resources:
            limits:
              cpu: 100m
              memory: 200Mi
            requests:
              cpu: 100m
              memory: 40Mi
          imagePullPolicy: {{ .Values.operator.image.pullPolicy }}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            privileged: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          volumeMounts:
            - name: cabundle
              mountPath: /etc/ssl/service
      volumes:
        - name: cabundle
          configMap:
            name: "ibm-spectrum-scale-cabundle"
            optional: true
