apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/instance: ibm-spectrum-scale
    app.kubernetes.io/name: cluster
  name: ibm-spectrum-scale-privileged
  namespace: ibm-spectrum-scale
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ibm-spectrum-scale-privileged
subjects:
- kind: ServiceAccount
  name: ibm-spectrum-scale-pmcollector
  namespace: ibm-spectrum-scale
- kind: ServiceAccount
  name: ibm-spectrum-scale-gui
  namespace: ibm-spectrum-scale
