apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    helm.sh/chart: {{ include "ibm-spectrum-scale.chart" . }}
  name: ibm-spectrum-scale-core
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - services
    verbs:
      - get
      - list
  - apiGroups:
      - "apps"
    resources:
      - deployments
      - statefulsets
    verbs:
      - get
      - list
