apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/instance: ibm-spectrum-scale
    app.kubernetes.io/name: operator
  name: ibm-spectrum-scale-leader-election-rolebinding
  namespace: ibm-spectrum-scale-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ibm-spectrum-scale-leader-election-role
subjects:
- kind: ServiceAccount
  name: ibm-spectrum-scale-operator
  namespace: ibm-spectrum-scale-operator
