apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    helm.sh/chart: {{ include "ibm-spectrum-scale.chart" . }}
    app.kubernetes.io/instance: ibm-spectrum-scale-core-operator
    app.kubernetes.io/managed-by: ibm-spectrum-scale-core-operator
    app.kubernetes.io/name: ibm-spectrum-scale-core-operator
    product: ibm-spectrum-scale-core
    release: ibm-spectrum-scale-core-operator
  name: ibm-spectrum-scale-operator
{{- if .Values.imageRegistrySecret }}    
imagePullSecrets:
  - name: "{{ .Values.imageRegistrySecret }}"
{{- end }}
